name: CI #obligatoire 

on: #obligatoire
  push: ~
  workflow_dispatch: ~

jobs: #obligatoire
  init:
    name: "Say hello"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  #recupere le code

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with: 
          node-version: latest
      
      - name: "List files"
        run: |
          ls
          echo "Second line"

      - name: "Install deps"
        run: npm ci # a la place de npm install

  build:
    name: "build project"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build"
        run: echo "Project built"

  tests:
    needs: ["build"]
    name: "test project"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Test"
        run: npm run test

  notify:
    name: "notify"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Notify"
        run: echo "CI OK"

      
